### ISSUE TITLE
Deleting traps

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1119]
Hey guys,
in the pfdump pull request I've seen these two commands:

```
drakvuf_remove_trap(drakvuf, info->trap, nullptr);
plugin->destroy_trap(info->trap);
```

Why are there two different methods for the semantically seemingly same thing? Or what is the different of both?
Thank you!

**Comment by BonusPlay** [comment]
`drakvuf_remove_trap` is a call to `libdrakvuf` which deletes the trap.

`plugin->destroy_trap` is a call to `plugins_ex`, which is a wrapper around `libdrakvuf` traps and provides a way to add data to the trap (and store `plugin*` instance pointer).

**Comment by Id3aFly** [comment]
Ok, that's exactly what I suspected from what I've seen so far. Thank you!

**Comment by tklengyel** [comment]
To expand on this, the third option to `drakvuf_remove_trap` is there in case the trap handler needs to retain some state before it's completely safe to remove. This is because there may be additional events already queued to be processed, some of which may need to be handled by the the same callback function you are just now trying to remove. The third option is specifying a callback function which is called when any state (ie. memory) is completely safe to remove.

**Comment by Id3aFly** [comment]
Thanks Tamas!
