### ISSUE TITLE
Complex plugin configuration

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#112]
I'm developing a plugin that will allow tracing of individual processes. My plan is to have support for multiple processes (tracing every instance of A.exe, B.exe, etc.). Also I want to define trace points (offsets) for each image. This will require a rather complex configuration structure and I'd like to discuss the best way for implementation.

My current concept is to follow (sort of) the "convention over configuration" principle: My plugin constructor would look for a specific .ini file in the CWD containing the basic config parameters (e.g. the names of the processes to trace). If the file is not found or invalid, the constructor fails and the plugin is deactivated. 

(For .ini parser, I have good experience with this one:  https://github.com/benhoyt/inih, but maybe we should simply stick to JSON)

After this a separate configuration (with the trap points and possibly other info) would be parsed for each target image from separate file with names corresponding to the image name, so users wouldn't need to edit a huge monolithic config file if they'd like to add/remove targets. 

This way we don't have to touch the main argument parser, but I wonder if this approach could be made a "standard" for plugins and thus supported with some helper functions at the level of libdrakvuf if needed?

What do you think?

**Comment by tklengyel** [comment]
For plugins requiring more detailed configuration input this approach sounds fine, the main argument parser would just need a single new addition to tell the plugin where to load the configuration file from. Whether that's JSON or something else that's IMHO entirely the plugin developers' choice. If it would require the installation of extra packages we might have the plugin disabled by default though.

For adding trap's within the address space of a process I've just finished #111, so that both simple VA points in a process as well as loaded library RVA's can be trapped. So for example if you have the Rekall profile for a loaded library, you could trap specific API calls in there. So this is what I assume you meant by "trace points". 

Also, an important issue that we may need to tackle is if traps in a process become stale because Windows' copy-on-write actually moved the code-page to a new location. Since we have stealth breakpoints the new location would not have the breakpoints anymore and we could miss traps afterwards. This might require some reverse engineering to find the CoW routine in Windows and keep an eye on it.

**Comment by v-p-b** [comment]
I've been putting together some code to test the data structures needed and I think the ones provided  by [STL containers](http://en.cppreference.com/w/cpp/container) provide a more convenient and "more C++" way than Glib that is generally used for this purpose right now. According to my tests some of these templates require support for C++11 but if I understand correctly the current build configuration supports this through `AX_CXX_COMPILE_STDCXX_11`. Is there a reason to stick with GLib or using STL is acceptable in case of plugins?

Regarding CoW: If I understand correctly in case of "well behaving" programs we'll trap addresses on RX pages so writes shouldn't happen. This may not be the case with self-modifying malware for example, but defining static trap addresses in case of these would be another challenge anyway. Or am I missing something?

**Comment by tklengyel** [comment]
Yes, plugins can use any C++11 features, so there is no requirement to use GLib.

CoW will be a problem when we are monitoring shared libraries for example but we can digg into it more as we encounter actual problems.
