### ISSUE TITLE
Proper way to enable ipt plugin

### ISSUE THREAD

**Issue by archercreat** [tklengyel/drakvuf#1392]
Hello @tklengyel, could you point me to the right direction on how to use ipt plugin?
```
1644579505.510711 Starting plugins
1644579505.510715 Starting plugin ipt
Failed to get trace buffer size
1644579505.510848 [IPT] Failed to enable IPT on vCPU 0
```
I'm having trouble enabling ipt under xen on my bare metal server.
CPU: `i5-5300U`
Xen: `v4.16`
virt_caps: `pv hvm hvm_directio pv_directio hap shadow iommu_hap_pt_share gnttab-v1 gnttab-v2`
It looks like a xen problem because I do have an access to intel pt when not in the xen context.
Thanks in advance.

**Comment by archercreat** [comment]
I forgot to include `vmtrace_buf_kb = 8192` to my vm config but once i did i now get the following error:
```
$ sudo xl create ../win7.cfg
Parsing config from ../win7.cfg
libxl: error: libxl_create.c:702:libxl__domain_make: domain creation fail: Invalid argument
```

**Comment by archercreat** [comment]
This is odd because while I'm not in xen context I can use `perf` utility with `intel_pt`:
```
$ sudo perf record -e intel_pt//u ls
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.058 MB perf.data ]
```
And while i'm in xen:
```
$ sudo perf record -e intel_pt//u ls
event syntax error: 'intel_pt//u'
                     \___ Cannot find PMU `intel_pt'. Missing kernel support
```
Looks like that xen just does not support intel_pt for some reason.
Sorry if its a wrong place to ask but there are not much info on this feature.

**Comment by tklengyel** [comment]
Well, your dom0 kernel version is way too old, you need at least 5.11 to be able to use PT on Xen. Even then, you won't be able to use perf like that anymore in dom0 so don't even try. But also if Xen says no vmtrace feature is available that means Xen didn't detect your CPU having the required features. If you are certain your CPU has it you need to investigate why Xen says otherwise.

**Comment by icedevml** [comment]
@archercreat Please note that DRAKVUF is using "external IPT" feature. This means: the DRAKVUF on Dom0 is asking Xen to enable IPT for some DomU. The DRAKVUF is explicitly asking Xen to do it, using "proprietary" Xen API.

I belive normal tools don't care whether they are on bare metal or in the VM. They are just asking the current system's kernel to set appropriate MSRs related to IPT directly. When you are running under hypervisor, the hypervisor would need to intercept that MSR writes and perform a lot of additional logic on top of that.

A few months ago the Xen behavior was simply to intercept MSR write attempts and deny them. The only way to enable IPT was through explicitly asking Xen. If this was not changed in the meantime, that would be an explanation why normal tools don't work under Xen.

**Comment by icedevml** [comment]
```
libxl: error: libxl_create.c:702:libxl__domain_make: domain creation fail: Invalid argument
```

I think the reason is one of the following (ordered from the most probable till least probable in my opinion):

1. Your CPU supports IPT in general, but it doesn't support it in VT-x operation, this is the case for some CPU generations (the ones released early when IPT itself was introduced)
2. Your Xen hypervisor version doesn't support IPT
3. Your Linux kernel is missing necessary patches for Xen integration
3. As Tamas said, IPT might simply not be correctly detected by Xen for the reason different than in point (1)

**Comment by archercreat** [comment]
@icedevml Thank you for clarification. I'll get my hands on xeon processor some time in the future but for now my `i5-5300u` is just too old for ipt.

Think this is probably an issue here because kernel update did not help, nor switching to different xen version.
> Your CPU supports IPT in general, but it doesn't support it in VT-x operation, this is the case for some CPU generations (the ones released early when IPT itself was introduced)

Closing this issue, thanks everyone for the help!
