### ISSUE TITLE
proctracer: trap in one dll will trap all processes who used that

### ISSUE THREAD

**Issue by zdzhjx** [tklengyel/drakvuf#143]
I test proctracer by running notepad.exe, only function kernel32.dll:CreateFileW in traced api lists.
In function trace_cb, it seems that the function invoked by all the  process. I tested it by print the CR3 value.

I think because we used the code:  lookup_type = LOOKUP_NONE, how can we resolve it?
Is it possible to use LOOKUP_PID?

Thanks.

**Comment by v-p-b** [comment]
I suspect that this is because Windows optimizes module loading by keeping only one copy of common DLLs in memory and just maps the same physical addresses to the virtual address spaces of different processes (see copy-on-write [here](http://www.tenouk.com/WinVirtualAddressSpace.html) for example). 

Since PROCTRACER works with physical addresses this can't be easily resolved, but the DLLs you mentioned are actually used as an interface to the kernel, tracing them don't seem to have more benefit then simply using the SYSCALL plugin. PROCTRACER is meant to instrument/monitor process-specific information (not caring about what happens in NTDLL for example after an API call), so instrumenting kernel interfaces seems to be out of the scope of this plugin.

**Comment by zdzhjx** [comment]
Yes, the copy-on-write affect the traps, but if LOOKUP_PID can make it work?

I take kernel32.dll:CreateFileW as an example, in fact, I need to get data after the API call is done, and I need to trace some 3rd dll files.

**Comment by v-p-b** [comment]
I don't think LOOKPU_PID has anything to do with this.

If you need to trace KERNEL32 for a given process, I suggest you to filter PROCTRACER output for a given CR3 value for now (maybe I'll implement some kind of extra filtering in the callback later).

**Comment by zdzhjx** [comment]
Thanks， filtering by CR3 is the right way, and  I will close this issue.
