### ISSUE TITLE
Dravuf on arm64 errors

### ISSUE THREAD

**Issue by BlackDeeer** [tklengyel/drakvuf#1614]
Hello

I am attempting to implement Drakvuf on arm64 architecture using the tutorial provided at https://github.com/drakvuf-on-arm/drakvuf-on-arm. However, I am encountering compilation errors while executing make command on the git branch drakvuf-acsac-artifact-eval. 

![arm](https://user-images.githubusercontent.com/36566960/222098265-9f2cb5f6-e481-44ce-9597-636a9f0bcf7c.png)
![arm2](https://user-images.githubusercontent.com/36566960/222098285-207c062b-6093-4df0-ba70-88f75a4d7157.png)

Since this branch is a bit outdated, I am assuming that encountering issues is expected. And, when attempting to build on the main branch of Drakvuf, I encounter errors that appear to be specific to the ARM architecture

![Screenshot_20230301_095446](https://user-images.githubusercontent.com/36566960/222098923-1b4e4b48-499f-49c0-b62d-a9c17487152c.png)

Are there any plans to enable arm support on the main branch?

Thank you.

**Comment by tklengyel** [comment]
As you guessed the issues you are seeing is because some of the API used in that branch is now outdated. There are no plans right now to get this up-to-date and merged in the main, but mainly because noone is working on it. Some critical pieces are still need to be merged upstream into Xen to make that viable.
