### ISSUE TITLE
QUery for drakvuf

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#223]
Hi,

My questions are
> DOes drakvuf requires modification in the hypervisor?
>can it work for all version of Xen
>can it support linux. how to go for it?
Thanks

**Comment by tklengyel** [comment]
Right now it does require a couple extra modifications to Xen. These changes have been upstreamed and will be part of Xen 4.8 that will be released sometime in December. DRAKVUF will not work with all versions of Xen, generally DRAKVUF needs the latest Xen version. If you have some older version of Xen you can fall back to older versions of DRAKVUF but keep in mind that those are not supported anymore. Adding Linux support should be relatively simple but the DRAKVUF-plugins are specifically targeting Windows right now. So those would have to evaluated on an individual bases whether they make sense for Linux or not.

**Comment by Preetixen** [comment]
Ok thanks tamas for reply.

From some days there is one more question  that is running in my mind. 

In which category of virtualization, are you going to classify your system and why?
I mean:  type I or type II
Xen is type I (baremetal hypervisor). however, in your system, hypervisor (Xen) is hosted on a operating system.

If we say DRAKVUF is based on hosted hypervisor then again Xen is creating confusion as it is type I hypervisor.

Please clarify??
Thanks

**Comment by tklengyel** [comment]
DRAKVUF is not a hypervisor so your question doesn't really apply.

**Comment by Preetixen** [comment]
Sorry, I think i wrote in incorrect way..

My question should have been like this: Is DARKVUF is designed for monitoring VM in hosted hypervisor or baremetal systems...

As Xen is used in implementation which is baremetal hypervisor then why a hosted OS is needed for drakvuf setup? (Ubuntu) 

Thanks.
Please provide some indea as you have a great domain knowledge of this field.

**Comment by tklengyel** [comment]
I think you are confusing things. When you are running an OS on Xen the
hypervisor is Xen which is type 1. For us this is pretty much irrelevant.
Drakvuf has no dependency on Ubuntu or Debian, you can use whatever Linux
distro you want. It would also likely work easily from FreeBSD. But that is
simply because convenience libraries like libxc have been written for these
OSes. You could write your own libxc driver for Windows if you are so
inclined. Same stands for Xen as well. We have no absolute requirement to
run on Xen, it just happens that its the only hypervisor exposing the
necessary features.
