### ISSUE TITLE
How does DRAKVUF handle trace execution of modern operating systems with context switching among threads of a process

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#254]
Hi,
I have a doubt. For multi-threaded programs (which most of commercial programs are), the system calls made by its threads could be interleaved, and the combined trace for that process would be non-deterministic.
How does the DRAKVUF handle such situations?

Thanks

**Comment by tklengyel** [comment]
Xen serializes all `VMEXIT`s with locks and sends the events to DRAKVUF on a single ring buffer. On multi-core systems it is nondeterministic which core receives the lock first within Xen. Thus if you are running the same process twice on multi-core systems the traces won't 100% match. But I don't think it would 100% match on a single-core system either because there are other random factors that can affect the traces.
