### ISSUE TITLE
Linux VM -  libdrakvuf initialization failed

### ISSUE THREAD

**Issue by chainzinger** [tklengyel/drakvuf#266]
Hi,

Im trying to use drakvuf for tracing syscalls of Linux VMs (debian 8 & ubuntu 16.04). After calling drakvuf with  _sudo ./drakvuf/src/drakvuf -r /root/ubuntu16.json -d 8_ the following returns

_DRAKVUF v0.5-ffb7229
Failed to register singlestep for vCPU 0
Failed to initialize DRAKVUF_

With enabled debugging:

_DRAKVUF v0.5-ffb7229
Starting DRAKVUF initialization
Init VMI on domID 8 -> ubuntu16
Failed to register singlestep for vCPU 0
starting close_vmi_drakvuf
close_vmi_drakvuf finished
libdrakvuf initialization failed
Failed to initialize DRAKVUF_

Using drakvuf on a Windows7 VM works without a problem.
The windows7 VM was installed based on your template from drakvuf.com. The both linux VMs were installed by using xen-tools (xen-create-image). 

Could it be possible that some of the values of your template (e.g. _seclabel='drakvuf:vm_r:drakvuf_domU_t' or altp2mhvm = 1_) are necessary to get drakvuf working?

I added a file with the basic information about the xen & vm setup: 
[drakvuf_configuration.txt](https://github.com/tklengyel/drakvuf/files/1010497/drakvuf_configuration.txt)

**Comment by tklengyel** [comment]
On May 18, 2017 04:20, "chainzinger" <notifications@github.com> wrote:

Hi,

Im trying to use drakvuf for tracing syscalls of Linux VMs (debian 8 &
ubuntu 16.04). After calling drakvuf with *sudo ./drakvuf/src/drakvuf -r
/root/ubuntu16.json -d 8* the following returns



*DRAKVUF v0.5-ffb7229 Failed to register singlestep for vCPU 0 Failed to
initialize DRAKVUF*

With enabled debugging:








*DRAKVUF v0.5-ffb7229 Starting DRAKVUF initialization Init VMI on domID 8
-> ubuntu16 Failed to register singlestep for vCPU 0 starting
close_vmi_drakvuf close_vmi_drakvuf finished libdrakvuf initialization
failed Failed to initialize DRAKVUF*

Using drakvuf on a Windows7 VM works without a problem.
The windows7 VM was installed based on your template from drakvuf.com. The
both linux VMs were installed by using xen-tools (xen-create-image).

Could it be possible that some of the values of your template (e.g.
*seclabel='drakvuf:vm_r:drakvuf_domU_t'
or altp2mhvm = 1*) are necessary to get drakvuf working?


Yes, they are all necessary. My guess is that you setup your VMs as PV,
which won't work.

I added a file with the basic information about the xen & vm setup:
drakvuf_configuration.txt
<https://github.com/tklengyel/drakvuf/files/1010497/drakvuf_configuration.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tklengyel/drakvuf/issues/266>, or mute the thread

**Comment by chainzinger** [comment]
Thanks for the advice. 
I created an Ubuntu PV. Now drakvuf works fine with it.
