### ISSUE TITLE
Xen boot process stuck at Loading Initial Ram Disk

### ISSUE THREAD

**Issue by JohnPeng47** [tklengyel/drakvuf#368]
Title says it all. Running Xen 4.9 on Ubuntu 16.0.4

From issue #215 , @tklengyel you said that the most likely cause was because checkpolicy or the XSM module was not installed. Are these two modules automatically configured to install or do I have to manually configure the build to install them?

**Comment by tklengyel** [comment]
We no longer use XSM with DRAKVUF so that is definitely not the problem. You will need to get access to the boot log of the system so you can debug it, as in https://wiki.xenproject.org/wiki/Xen_Serial_Console. Since this is not a DRAKVUF issue, but a Xen issue, I would recommend asking for help on the xen-users mailinglist if you can't figure out why Xen is not booting on your machine.
