### ISSUE TITLE
Xen didn't boot

### ISSUE THREAD

**Issue by ultrapikachu** [tklengyel/drakvuf#584]
I installed drakvuf on fresh system with instruction on webpage

After xen install, i try reboot my machine but after grub screen system going to BusyBox

I can boot system with Xen

What will i do

**Comment by ultrapikachu** [comment]
"Failed to mount /proc/xen."

**Comment by Dos98** [comment]
Same I am also stuck here. Today I also tried installing fresh Drakvuf on Ubuntu 18.04.02. Since Ubuntu 18 has gcc version 7 so build and installation was completed without any error. But when I booted into xen it was a completely Black screen with pointer.

I am not sure what my error is.
I will look more into it tomorrow. As I have exam in the morning.

**Comment by tklengyel** [comment]
Make sure your system is set to boot in legacy mode. If it is in legacy mode then you will need a system that has a serial port to debug why it's not booting.

**Comment by ultrapikachu** [comment]
Log from boot.log

[FAILED] Failed to mount /proc/xen.
[FAILED] Failed to start Load Kernel Modules.

Reason of kernel error
Failed to insert 'xen_evtchn': No such device
 Failed to insert 'xen_privcmd': No such device

I installed all thing

**Comment by Dos98** [comment]
We can close this now. It boots in Legacy Mode.
