### ISSUE TITLE
Running DRAKVUF in VMWare workstation with nested virtualization support

### ISSUE THREAD

**Issue by zashraf1337** [tklengyel/drakvuf#6]
Hi,

I was curious to see if this setup will work, so I am going to document the results here.

So far by enabling nested virtualization in VMWARE Workstation 9, I see

zashraf@ubuntu12:~$ sudo modprobe msr
zashraf@ubuntu12:~$  sudo rdmsr 0x3A
5

and /proc/cpuinfo also shows vmx and ept in flags.

===

Now following the instructions from drakvuf.com I am working on resolving the rekall_profile issue as running process_list says

VMI_ERROR: Rekall profile error on line 1: '[' or '{' expected near distorm.

BTW I am using latest version of Rekall (1.4).

Can anyone post how rekall profiles look from a working setup?

Thanks

**Comment by tklengyel** [comment]
I still have doubts about DRAKVUF working in such a nested setup but I guess it's worth a shot ;) It seems like the Rekall profile generation didn't work and you don't have valid json file. Try using Rekall 1.1.0 instead.

**Comment by tklengyel** [comment]
A valid Rekall profile should look something like this: https://github.com/libvmi/libvmi/blob/master/tests/ntoskrnl.pdb.32962337f0f646388b39535cd8dd70e82.rekall.json

**Comment by zashraf1337** [comment]
My bad, I had added a print statement in distorm init code, to oslve an issue I ran into that print statement got in to the generated profile, so process_list works - now onto trying drakvuf

**Comment by zashraf1337** [comment]
Got stuck on VMI ERROR: EPT not supported although xl dmesg shows EPT is there, but turns out that it does not enable HAP - and that is because of 
http://xenbits.xen.org/xsa/advisory-60.html

**Comment by tklengyel** [comment]
I'm not sure that XSA is the reason - that concerns cases with pci passthrough AFAICT.

**Comment by zashraf1337** [comment]
So I went in 
vmx/vmx.c in xen source (that you downloaded when following instructions from drakvuf.com)
     commented out the condition on around 1684 where ept would not be enabled if vmx_pat is not
     present
     and changed it to 
     only depend on ept and not on checking vmx_pat

compiled xen as directed on drakvuf.com, rebooted and checked xl dmesg and HAP messages were fine.

I then succeeded with ./src/drakvuf -d <rekall profile> <domid>

**Comment by tklengyel** [comment]
Wow, that's great news! =)

**Comment by tklengyel** [comment]
Does it produce the expected output?

**Comment by tklengyel** [comment]
FYI, if you upgrade to Xen 4.5, there is a command line option you can set that enables you to bypass this issue without having to recompile:

force-ept (Intel)
    = <boolean>
    Default: false

Allow EPT to be enabled when VMX feature VM_ENTRY_LOAD_GUEST_PAT is not present.

Warning: Due to CVE-2013-2212, VMX feature VM_ENTRY_LOAD_GUEST_PAT is by default required as a prerequisite for using EPT. If you are not using PCI Passthrough, or trust the guest administrator who would be using passthrough, then the requirement can be relaxed. This option is particularly useful for nested virtualization, to allow the L1 hypervisor to use EPT even if the L0 hypervisor does not provide VM_ENTRY_LOAD_GUEST_PAT.
