### ISSUE TITLE
Networking infrastructure questions

### ISSUE THREAD

**Issue by rstocktox** [tklengyel/drakvuf#64]
Hi Tamas,  
I don't see clearly what's the usual network topology used with Drakvuf but according to the _clone.pl_ script I assume the DomUs are behind a virtual network with a VLAN for each clone with Openvswitch, I wonder how the clones can access Internet having the same MAC address, I see how you set a different clone IP address thanks to the _preconfig.sh_ script but I don't have a clue on what network interfaces are shared between Dom0 and the DomUs or even who is doing NAT (MAC NAT?).

How are ebtables, iptables and Openvswitch mixed altogether to accomplish this task?  
Is your Xen networking script different to the "vif-openvswitch" originally included in Xen?  
Can you elaborate on this?

Many thanks in advance,

Robert

**Comment by tklengyel** [comment]
So the MAC address being the same is only a problem if the clones are living on the same bridge. Since with Open vSwitch we can segregate each clone to it's own VLAN, there is no MAC address collision. In dom0 you just bring up the other-end of the VLAN interface with unique IP on a unique subnet matching what you inject with preconfig.sh. This is the script I use:

```
#!/bin/bash
modprobe 8021q
ifconfig xenbr1 up

for i in `seq 1 $1`;
do
    vconfig add xenbr1 $i
    ifconfig xenbr1.$i up
    ifconfig xenbr1.$i 192.168.$i.1 netmask 255.255.255.0 up
    iptables -A FORWARD -i xenbr1.$i -o !xenbr0 -j DROP
done
```

Afterwards, you can just use the normal iptables NAT to let traffic flow freely (`iptables -t nat -A POSTROUTING -o xenbr0 -j MASQUERADE`). Right now I also inject a custom DNS server to be used too, so you should have some DNS forwarded setup (I use dnschef). I'm using the stock vif-openvswitch script from Xen.

I think it's time I do another Wiki entry on this setup as well =)

**Comment by rstocktox** [comment]
Tamas,
you're very kind of wasting your time with so detailed explanations.

What about keeping the same ip address inside the clones using NAT rules for every _xenbr1.$i_ interface? This way...
`iptables -t nat -A PREROUTING -i xenbr1.$i -j MASQUERADE`  
 Would it be possible?

**Comment by tklengyel** [comment]
It's possible but it's a lot more involved. I had that working with [honeybrid](https://github.com/tklengyel/honeybrid) by enabling it sniffing on the VLAN trunk interface and performing NAT based on the VLAN id. Feel free to give it a try but it's not currently supported so you would probably have to do quite a bit of experimentation on your own to get it working.

**Comment by tklengyel** [comment]
I've added a [Wiki entry](https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup) on how to setup the automated analysis loop. Feel free to reopen the issue if you have more questions.
