### ISSUE TITLE
Faster breakpoints with VMI_EVENT_RESPONSE_SET_EMUL_INSN ?

### ISSUE THREAD

**Issue by mtarral** [tklengyel/drakvuf#667]
Hi,

I would like to open a discussion regarding the possibility offered by LibVMI's reponse `SET_EMUL_INSN`.

The current implementation in Drakvuf relies on alternate P2M, a breakpoint flow looks like this:

1. breakpoint hit
2. interrupt callback
3. response: `singlestep` + `change p2m`
4. vcpu is singlestepping
5. singlestep callback
6. reponse: `stop singlestep` + `change p2m`

The singlestep could be avoided using intruction emulation response, as described by @tklengyel on the mailing list:
https://lists.xenproject.org/archives/html/xen-devel/2016-09/msg01373.html

> When responding to a SOFTWARE_BREAKPOINT event (INT3) the monitor subscriber
normally has to remove the INT3 from memory - singlestep - place back INT3
to allow the guest to continue execution. This routine however is susceptible
to a race-condition on multi-vCPU guests. By allowing the subscriber to return
the i-cache to be used for emulation it can side-step the problem by returning
a clean buffer without the INT3 present.

The breakpoint flow would look like this:
1. breakpoint hit
2. interrupt callback
3. response: `emulate instruction with previous opcode`

-> I haven't been benchmarking libvmi, nor Drakvuf, but even with the emulation (in-kernel), it should be way faster ?
cc @skvl , @icedevml maybe you have already been thinking or working on this ?

I have been working on a small example, to be integrated into Libvmi:
https://github.com/libvmi/libvmi/pull/793

If that's the case, we could need a disassembler, so #483 is related.

Thanks.

**Comment by tklengyel** [comment]
I've added the instruction emulation capability via vm_event to Xen a couple years ago before altp2m was added. I prefer altp2m because the instruction emulator in Xen is incomplete.

**Comment by skvl** [comment]
@mtarral as far as I know emulation should make the process faster.

Even more both approaches could be mixed. A simple emulator could process several frequent cases and single step in other cases.

**Comment by mtarral** [comment]
@skvl I also agree that combining both method and having a mixed approach could be beneficial.

We could use the robust breakpoints with altp2m and singlestep for specific breakpoints in DLLs and in non-trivial locations, and use fast breakpoints for all syscalls for example, since they are triggered very frequently and should be processed as fast as possible.

Also, the first instruction of the syscalls implementation should be very standard instructions like `mov` or `push`, so even though the Xen emulator is incomplete, it should support these since a long time.

**Comment by tklengyel** [comment]
> Also, the first instruction of the syscalls implementation should be very standard instructions like mov or push, so even though the Xen emulator is incomplete, it should support these since a long time.

You can't guarantee that without actually doing disassembly for each instance when it is trapped.

**Comment by tklengyel** [comment]
>  I haven't been benchmarking libvmi, nor Drakvuf, but even with the emulation (in-kernel), it should be way faster ?

Not really, last time it was checked altp2m-based breakpoints were on-par with the emulator. Remember that the emulator still likely has to parse the pagetable in the guest, perform the emulation & then write-back results to memory. While you save the extra round-trip of the singlestep, altp2m switching is a lot faster then the emulation, so it pretty much equals out the extra round-trip.

But of course you are welcome to conduct a benchmark and see for yourself. If you intend to use the instruction emulation only in instances where it's a `nop`, then you might gain some performance. But this is not something that's universally applicable, adds a massive complexity to an already quite complex system, and is known to have issues. So I won't be adding support to it to DRAKVUF because it's not something I want to support in the general case. For your specific usecase you are welcome to fork and use whatever works best.
