### ISSUE TITLE
CR3 data type mismatch?

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#7]
Take the following two pieces of code:
https://github.com/tklengyel/drakvuf/blob/master/src/vmi.c#L270 
https://github.com/tklengyel/drakvuf/blob/master/src/vmi.c#L546

In the first case `cr3` is defined as `reg_t` which is typedef'd as `uint64_t` by LibVMI, since  the value is retreived by `vmi_get_vcpureg()`. In the second case the `dtb` variable is defined as `uint32_t` since the value is retreived using `vmi_read_32_va()`. This is causing me some headaches when trying to use those values as keys of a hash table for example, but probably this is not the only problematic use case.

Can you please provide some advice on how to resolve this issue properly?

**Comment by tklengyel** [comment]
While it is generally safe to read only 32-bit of the DirectoryTableBase value of _KPROCESS as the physical addresses used are always < 0x7FFFFFFF, on 64-bit Windows it has a type of unsigned long long. So technically these could be > 7FFFFFFF albeit never being so.

The fix is to switch between vmi_read_32 and vmi_read_64 depending on which version we are dealing with. I'll fix this inconsistency shortly. Thanks for pointing it out ;)

**Comment by v-p-b** [comment]
Thank you!

**Comment by tklengyel** [comment]
Check out https://github.com/tklengyel/drakvuf/tree/dtb_read_fix

**Comment by tklengyel** [comment]
As you see vmi_read_addr_va actually already takes care of this (reading 32 vs 64 bits depending on the paging type). So this is the function that should be used when dealing with pointers.

**Comment by v-p-b** [comment]
Elegant! Still, if I understand correctly, I have to take care of lengths when comparing register values with pointers taken from _KPROCESS since `reg_t` is always 64 bit. (This is OK as long as I'm aware that I have to do it)

**Comment by v-p-b** [comment]
Thank you, I think this issue can be closed.
