### ISSUE TITLE
Injector stalls (seemingly) randomly

### ISSUE THREAD

**Issue by dorpvom** [tklengyel/drakvuf#79]
Hi,
The injector seems to randomly stall at injection.
By random I mean that I call the injector - it stalls (see below) - then I destroy and restore the VM, reuse the exact same line with just the new domid inserted and it works. Any leads?
Btw. this did happen with older versions too, at least I observed it with a November release as well.

$ sudo injector /root/win.rekall.json 2 3320 "cmd.exe"
Init VMI on domID 2 -> win
Rekall profile: structure member 'Rip' not found
Failed to find offset for _KTRAP_FRAME:Rip
Reservation increased? 0 with new gfn: 0x3a764d
Xen altp2m view created with idx: 1 idr: 2
Injector starting cmd.exe through PID 3320
Target PID 3320 with DTB 0xb9e57180 to start 'cmd.exe'
Starting injection loop
Current thread: 92. Base: 0x84b6a5d0. ApcQueueable: 1.
Kernel stack base: 0x8c84bed0. Limit: 0x8c849000
Found target pid of 3320. PEB @ 0x7ffdf000. LDR @ 0x770f7880. INLOADORDER @ 0x1117f0.
Found module in PID 3320: taskmgr.exe
Found module in PID 3320: ntdll.dll
Found module in PID 3320: kernel32.dll
	CreateProcessA @ 0x75482082
APC Normal routine @ 0x75482082. Kernel routine @ 0x828c002f
APC injected at 0x8c849000
Wrote trap to 0x75482082. Backup: 139

Here it stalls.

**Comment by tklengyel** [comment]
Yes, I've observed that too sometimes. I don't yet know what could be the root cause but it seems the injected APC message never gets processed by the hijacked thread. It could be just an unfortunate timing of picking a thread to inject the APC into that was about to terminate (DRAKVUF just grabs the first thread that gets scheduled of the target process). Normally what I do is that I create a snapshot of the VM and then try injection on it. If it works, that it will work every time the snapshot is restored.

**Comment by dorpvom** [comment]
FYI, I observed this oftentimes after a first succesfull drakvuf run. So I have a stable snapshot, use drakvuf to download a file from the web and after that it stalls when instrumenting the binary. If you at some point want to debug the issue this might be helpful. The system is then not accepting any injection.
