### ISSUE TITLE
single stepping in drakvuf

### ISSUE THREAD

**Issue by chengsteven** [tklengyel/drakvuf#873]
What's the best way to single step in drakvuf without interrupting drakvuf internals? 

e.g. I want to trap on a certain breakpoint or memaccess, then single step a few times. After some condition, remove the single step event and continue normal operation.

**Comment by tklengyel** [comment]
This is not currently supported, there is no "singlestep" callback. The only traps supported through DRAKVUF are: `BREAKPOINT,MEMACCESS,REGISTER,DEBUG,CPUID`. This is because singlestepping is used heavily in DRAKVUF to step-over all the other types of events and relies on an internal handler being called for that to be handled appropriately. It would theoretically be possible to add the singlestep callback so the user can decide to keep it going after a breakpoint/memaccess, but it's not currently implemented.
